// <auto-generated />
using System;
using FuseboxHomework.Core.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuseboxHomework.Core.EF.Migrations
{
    [DbContext(typeof(FbDbContext))]
    partial class FbDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("FuseboxHomework.Core.EF.Model.HourlyElectricityPrice", b =>
                {
                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("DateTime");

                    b.ToTable("HourlyElectricityPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
